// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant_table_control_api.Context;

#nullable disable

namespace Restauranttablecontrolapi.Migrations
{
    [DbContext(typeof(ContextData))]
    [Migration("20240403183250_02")]
    partial class _02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant_table_control_api.Entity.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Road")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients_Entity");
                });

            modelBuilder.Entity("Restaurant_table_control_api.Entity.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("restaurantTableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("restaurantTableId");

                    b.ToTable("Commands_Entity");
                });

            modelBuilder.Entity("Restaurant_table_control_api.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Expiration_Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Purchase_Price")
                        .HasColumnType("float");

                    b.Property<double?>("Sale_Price")
                        .HasColumnType("float");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Product_Entity");
                });

            modelBuilder.Entity("Restaurant_table_control_api.Entity.ProductDatail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Sale_Price")
                        .HasColumnType("float");

                    b.Property<int?>("commandId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("date_Of_Sale")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("commandId");

                    b.ToTable("productDatails");
                });

            modelBuilder.Entity("Restaurant_table_control_api.Entity.RestaurantTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RestaurantTable");
                });

            modelBuilder.Entity("Restaurant_table_control_api.Entity.Command", b =>
                {
                    b.HasOne("Restaurant_table_control_api.Entity.RestaurantTable", "restaurantTable")
                        .WithMany("commands")
                        .HasForeignKey("restaurantTableId");

                    b.Navigation("restaurantTable");
                });

            modelBuilder.Entity("Restaurant_table_control_api.Entity.ProductDatail", b =>
                {
                    b.HasOne("Restaurant_table_control_api.Entity.Command", "command")
                        .WithMany("productDatails")
                        .HasForeignKey("commandId");

                    b.Navigation("command");
                });

            modelBuilder.Entity("Restaurant_table_control_api.Entity.Command", b =>
                {
                    b.Navigation("productDatails");
                });

            modelBuilder.Entity("Restaurant_table_control_api.Entity.RestaurantTable", b =>
                {
                    b.Navigation("commands");
                });
#pragma warning restore 612, 618
        }
    }
}
